[tool.pyright]
pythonVersion = "3.10"

typeCheckingMode = "strict"
reportUnusedImport = true
reportUnusedVariable = false
reportUnknownMemberType = false
reportCallInDefaultInitializer = true
reportImplicitStringConcatenation = true
